name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.12.11
          - 2.13.1
        jvm:
          - openjdk@8
          - openjdk@1.14
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Cache .jabba
        id: cache-jabba
        uses: actions/cache@v1
        with:
          path: ~/.jabba
          key: ${{ runner.os }}-jabba
      - name: Cache .sbt
        id: cache-sbt
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt
      - name: Set up ${{ matrix.jvm }}
        uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.jvm }}
      - name: Build and run tests
        run: sbt ++${{ matrix.scala }} clean compile octopusJS/test octopusCatsJS/test octopusScalazJS/test coverage octopusJVM/test octopusCatsJVM/test octopusScalazJVM/test octopusJVM/coverageReport octopusCatsJVM/coverageReport octopusScalazJVM/coverageReport
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
